name: Train Llama

on: push

jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, '#') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and tag the Docker image
        run: npm run ship
